#!/usr/bin/env node
const exec = require('child_process').exec;
const command = `dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'`
    + ` | grep -Ev '^method'`
    + ` | grep -Eo '("(.*)")|(\\b[0-9][a-zA-Z0-9.]*\\b)'`
    + ` | sed -E '2~2 a|'`
    + ` | tr -d '\\n'`
    + ` | sed -E 's/\\|/\\n/g'`
    + ` | sed -E 's/(xesam:)|(mpris:)//'`
    + ` | sed -E 's/^"|"$//g'`
    + ` | sed -E 's/"+/:/g'`
    + ` | sed -E 's/ +/ /g'`;

exec(command, (error, stdout, stderr) => {
    if (!error && stdout) {
        const metadata = stdout.trim().split(/\r?\n/g).reduce((metas, meta) => {
            const i = meta.indexOf(':');
            metas[meta.slice(0, i)] = meta.slice(i + 1);
            return metas;
        }, {});
        var output = metadata.title.replace(/&/g, ' and ');
    } else {
        var output = 'Open Spotify';
    }
    console.log(output);
});
